spring.main.banner-mode=off
server.port= 8002
spring.application.name=second-mgmt-service
#1.0	trace 100% requests ==> in development
#0.5	trace 50%
#0.1	trace 10%
#0.01	trace 1% ==> may be in production or this (0.05) depending on traffic volume.
#how many requests generate traces
management.tracing.sampling.probability= 1.0
# where to send tracing data
management.zipkin.tracing.endpoint=http://zipkin_elk:9411/api/v2/spans